# Generated by Django 3.2.2 on 2021-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0003_miembro_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='apellido_mat',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='apellido_pat',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='contraseña',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
