# Generated by Django 3.2.2 on 2021-05-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0004_auto_20210526_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='pin',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
